name:                bookbot
version:             0.1.0.1
github:              "eddsteel/bookbot"
license:             GPL-3
author:              "Edward Steel"
maintainer:          "edd@eddsteel.com"
copyright:           "GPL"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/eddsteel/bookbot#readme>

dependencies:
- base == 4.*
- JuicyPixels
- aeson
- authenticate-oauth
- bytestring
- cairo
- diagrams-core
- diagrams-lib
- diagrams-svg
- directory
- filepath
- http-conduit
- random
- regex-compat
- split
- svg-builder
- svgcairo
- text
- twitter-conduit
- twitter-types
- yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -Wunused-packages

executables:
  bookbot-auth:
    main:                Auth.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Auth
    dependencies:
    - bookbot

  scratch:
    main:                Scratch.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Scratch
    dependencies:
    - bookbot

  post:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - bookbot

tests:
  bookbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookbot
    - hspec
