name:                bookbot
version:             0.1.0.0
github:              "eddsteel/bookbot"
license:             GPL-3
author:              "Edward Steel"
maintainer:          "edward.steel@gmail.com"
copyright:           "GPL"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eddsteel/bookbot#readme>

dependencies:
- base >= 4.7 && < 5
- HandsomeSoup
- hxt
- twitter-conduit
- authenticate-oauth
- bytestring
- text
- twitter-types
- random
- directory

library:
  source-dirs: src

executables:
  bookbot-auth:
    main:                Auth.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Auth
    dependencies:
    - bookbot

  scratch:
    main:                Scratch.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Scratch
    dependencies:
    - bookbot

  bookbot-post:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookbot

tests:
  bookbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookbot
